### ISSUE TITLE
Unable to run docker image

### ISSUE THREAD

**Issue by ankitnayan** [weaveworks-plugins/scope-http-statistics#22]
On running the docker command I am getting
```
sh: 1: modprobe: not found
Unable to find kernel headers. Try rebuilding kernel with CONFIG_IKHEADERS=m (module)
chdir(/lib/modules/4.14.138-89.102.amzn1.x86_64/build): No such file or directory
Traceback (most recent call last):
  File "/usr/bin/http-statistics.py", line 294, in <module>
    kernel_inspector = KernelInspector()
  File "/usr/bin/http-statistics.py", line 57, in __init__
    self.bpf = bcc.BPF(EBPF_PROGRAM)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 343, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module /usr/bin/ebpf-http-statistics.c
```

**Comment by bboreham** [comment]
Please see the note at the top of the README:

> Note: This plugin needs a recent kernel version with eBPF support. It will not compile on current dlite and boot2docker hosts. You need /sys/kernel/debug/ in order to be able to build the eBPF program generated by the plugin.
