### ISSUE TITLE
Will not compile cannot find kconfig.

### ISSUE THREAD

**Issue by jasonrichardsmith** [weaveworks-plugins/scope-http-statistics#8]
```
sudo docker run --rm -it \
>       --privileged --net=host --pid=host \
>       -v /lib/modules:/lib/modules \
>       -v /usr/src:/usr/src \
>       -v /sys/kernel/debug/:/sys/kernel/debug/ \
>       -v /var/run/scope/plugins:/var/run/scope/plugins \
>       --name weaveworksplugins-scope-http-statistics weaveworksplugins/scope-http-statistics
[sudo] password for foo: 
In file included from <built-in>:316:
<command line>:5:10: fatal error: './include/linux/kconfig.h' file not found
#include "./include/linux/kconfig.h"
         ^
1 error generated.
Traceback (most recent call last):
  File "/usr/bin/http-statistics.py", line 294, in <module>
    kernel_inspector = KernelInspector()
  File "/usr/bin/http-statistics.py", line 57, in __init__
    self.bpf = bcc.BPF(EBPF_PROGRAM)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 197, in __init__
    raise Exception("Failed to compile BPF module %s" % src_file)
Exception: Failed to compile BPF module /usr/bin/ebpf-http-statistics.c
```

**Comment by jasonrichardsmith** [comment]
uname -r: 4.4.41-1-MANJARO
kconfig: kconfig-5.30.0-1-x86_64
